# Generated by Django 6.0.2 on 2026-02-28 23:11

import app_newmedia.registration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Recomendado: 300x300px, máximo 2MB', null=True, upload_to=app_newmedia.registration.models.user_profile_photo_path, verbose_name='Foto de Perfil')),
                ('pix_nome', models.CharField(blank=True, help_text='Nome que aparece no PIX', max_length=200, verbose_name='Nome do PIX')),
                ('pix_chave', models.CharField(blank=True, help_text='CPF, email, telefone ou chave aleatória', max_length=200, verbose_name='Chave PIX')),
                ('pix_favorecido', models.CharField(blank=True, help_text='Nome do titular da conta', max_length=200, verbose_name='Favorecido')),
                ('pix_banco', models.CharField(blank=True, help_text='Nome do banco', max_length=100, verbose_name='Banco')),
                ('dias_acesso', models.IntegerField(default=365, help_text='Quantidade de dias de acesso ao sistema', verbose_name='Dias de Acesso')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Quando o acesso expira (calculado automaticamente)', null=True, verbose_name='Data de Expiração')),
                ('plano', models.CharField(choices=[('gratuito', 'Gratuito'), ('premium', 'Premium'), ('vip', 'VIP')], default='gratuito', max_length=20, verbose_name='Plano de Assinatura')),
                ('tema_escuro', models.BooleanField(default=False, verbose_name='Usar tema escuro')),
                ('notificacoes_email', models.BooleanField(default=True, verbose_name='Receber notificações por email')),
                ('compartilhamento_publico', models.BooleanField(default=False, verbose_name='Permitir compartilhamento público de mídias')),
                ('total_midias', models.IntegerField(default=0, help_text='Contador automático de mídias do usuário', verbose_name='Total de Mídias')),
                ('total_anotacoes', models.IntegerField(default=0, help_text='Contador automático de anotações', verbose_name='Total de Anotações')),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP de Login')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Perfil')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'user_profile',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
