# Generated by Django 6.0.2 on 2026-04-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pix_banco',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pix_chave',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pix_favorecido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pix_nome',
        ),
    ]
