# Generated by Django 6.0.2 on 2026-04-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_add_social_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de Integração API'),
        ),
    ]
