# Generated by Django 6.0.2 on 2026-08-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userprofile_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fuso_horario',
            field=models.CharField(default='America/Sao_Paulo', help_text='Fuso horário atual do usuário para disparos precisos.', max_length=50, verbose_name='Fuso Horário'),
        ),
    ]
