# Generated by Django 6.0.2 on 2026-08-02 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_telefone', models.CharField(db_column='MEN_TELEFONE', max_length=20, verbose_name='Telefone do Contato')),
                ('men_nome', models.CharField(db_column='MEN_NOME', max_length=100, verbose_name='Nome do Contato')),
                ('men_dat', models.DateField(db_column='MEN_DAT', verbose_name='Data Agendada')),
                ('men_hora', models.TimeField(db_column='MEN_HORA', verbose_name='Hora Agendada')),
                ('men_ocorrencia', models.CharField(choices=[('agora', 'Agora'), ('todo_dia', 'Todo dia'), ('semanal', 'Uma vez na semana'), ('mensal', 'Uma vez no mês')], db_column='MEN_OCORRENCIA', max_length=20, verbose_name='Ocorrência')),
                ('men_mensagem', models.CharField(db_column='MEN_MENSAGEM', max_length=150, verbose_name='Mensagem')),
                ('men_status', models.BooleanField(db_column='MEN_STATUS', default=False, verbose_name='Enviado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'db_table': 'TBMENSAGEM',
                'ordering': ['-criado_em'],
            },
        ),
    ]
