# Generated by Django 6.0.2 on 2026-08-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='ultimo_disparo',
            field=models.DateTimeField(blank=True, db_column='MEN_ULTIMO_DISPARO', null=True, verbose_name='Último Disparo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='men_ocorrencia',
            field=models.CharField(choices=[('agora', 'Agora'), ('unico', 'Enviar no dia/hora acima'), ('todo_dia', 'Todo dia'), ('semanal', 'Uma vez na semana'), ('mensal', 'Uma vez no mês')], db_column='MEN_OCORRENCIA', max_length=20, verbose_name='Ocorrência'),
        ),
    ]
