# Generated by Django 6.0.2 on 2026-08-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_mensagem_ultimo_disparo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='men_ocorrencia',
            field=models.CharField(choices=[('agora', 'Agora'), ('unico', 'Enviar no dia/hora acima'), ('todo_dia', 'Todo dia'), ('semanal', 'Uma vez na semana'), ('mensal', 'Uma vez no mês'), ('dias_uteis', 'Enviar só em dias Uteis')], db_column='MEN_OCORRENCIA', max_length=20, verbose_name='Ocorrência'),
        ),
    ]
