# Generated by Django 6.0.2 on 2026-09-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_alter_mensagem_men_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='men_dia_semana',
            field=models.CharField(blank=True, choices=[('0', 'Segunda-feira'), ('1', 'Terça-feira'), ('2', 'Quarta-feira'), ('3', 'Quinta-feira'), ('4', 'Sexta-feira'), ('5', 'Sábado'), ('6', 'Domingo')], db_column='MEN_DIA_SEMANA', max_length=1, null=True, verbose_name='Dia da Semana'),
        ),
    ]
