# Generated by Django 6.0.2 on 2026-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0004_mensagem_men_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='men_mensagem',
            field=models.CharField(db_column='MEN_MENSAGEM', max_length=255, verbose_name='Mensagem'),
        ),
    ]
