# Generated by Django 6.0.2 on 2026-03-01 03:22

import app_newmedia.medias.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('pdf', 'PDF'), ('documento', 'Documento'), ('texto', 'Texto'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Enviando'), ('concluido', 'Concluído'), ('erro', 'Erro no Upload')], default='concluido', max_length=20, verbose_name='Status')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=app_newmedia.medias.models.user_media_path, verbose_name='Arquivo')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-criado_em'],
            },
        ),
    ]
