# Generated by Django 6.0.2 on 2026-03-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho'),
        ),
    ]
