# Generated by Django 6.0.2 on 2026-03-02 00:57

import app_newmedia.medias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_midia_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to=app_newmedia.medias.models.user_media_path, verbose_name='Miniatura'),
        ),
    ]
