# Generated by Django 6.0.2 on 2026-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaocompra',
            name='cartao_final',
            field=models.CharField(blank=True, max_length=10, verbose_name='Final do Cartão'),
        ),
        migrations.AddField(
            model_name='notificacaocompra',
            name='tipo_transacao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Transação (PIX/COMPRA)'),
        ),
    ]
