# Generated by Django 6.0.2 on 2026-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_notificacaocompra_cartao_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaocompra',
            name='origem',
            field=models.CharField(choices=[('NOTIFICACAO', 'Notificação'), ('EMAIL', 'E-mail')], default='NOTIFICACAO', max_length=20, verbose_name='Origem dos dados'),
        ),
    ]
