# Generated by Django 6.0.2 on 2026-09-01 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_notificacaocompra_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nubank, Itaú, Banco do Brasil', max_length=50, verbose_name='Nome da Instituição')),
                ('pacote_android', models.CharField(help_text='Ex: com.nu.production, com.itau, br.com.bb.android', max_length=100, verbose_name='Pacote do Android')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos_monitorados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Banco Monitorado',
                'verbose_name_plural': 'Bancos Monitorados',
                'db_table': 'carteira_banco_monitorado',
                'ordering': ['nome'],
                'unique_together': {('usuario', 'pacote_android')},
            },
        ),
    ]
