# Generated by Django 6.0.2 on 2026-04-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anota_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='pix_cidade',
            field=models.CharField(blank=True, default='Sua Cidade', max_length=100, null=True, verbose_name='Cidade do Favorecido'),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='pix_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
