# Generated by Django 6.0.2 on 2026-04-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anota_ai', '0002_anotacao_pix_cidade_anotacao_pix_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('lista_numerada', 'Lista Numerada'), ('checklist', 'Checklist'), ('pix', 'PIX'), ('link', 'Link')], max_length=20, verbose_name='Tipo'),
        ),
    ]
