# Generated by Django 6.0.2 on 2026-04-11 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_column='CAL_DATA', verbose_name='Data')),
                ('hora', models.TimeField(db_column='CAL_HORA', verbose_name='Hora')),
                ('titulo', models.CharField(db_column='CAL_COMPROMISSO', max_length=50, verbose_name='Compromisso')),
                ('cor', models.CharField(db_column='CAL_COR', default='#7C8EE0', max_length=15, verbose_name='Cor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compromissos',
                'db_table': 'TBCALENDARIO',
                'ordering': ['data', 'hora'],
            },
        ),
    ]
