# Generated by Django 6.0.2 on 2026-05-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='lembrete_enviado',
            field=models.BooleanField(default=False, verbose_name='Lembrete Enviado'),
        ),
    ]
