# Generated by Django 6.0.2 on 2026-05-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_compromisso_lembrete_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='antecedencia_minutos',
            field=models.IntegerField(choices=[(0, 'Na hora do compromisso'), (15, '15 minutos antes'), (30, '30 minutos antes'), (60, '1 hora antes'), (120, '2 horas antes'), (1440, '1 dia antes')], default=120, verbose_name='Avisar com antecedência de'),
        ),
    ]
