# Generated by Django 6.0.2 on 2026-08-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_compromisso_antecedencia_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('status', models.CharField(choices=[('ok', '✅ Enviado'), ('sem_compromissos', '💭 Sem compromissos na janela'), ('erro', '❌ Erro')], max_length=20, verbose_name='Status')),
                ('mensagens_enviadas', models.IntegerField(default=0, verbose_name='Mensagens enviadas')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes / Log')),
            ],
            options={
                'verbose_name': 'Log do Cron',
                'verbose_name_plural': 'Logs do Cron (WhatsApp)',
                'db_table': 'TBLOGCRON',
                'ordering': ['-executado_em'],
            },
        ),
    ]
