# Generated by Django 6.0.2 on 2026-03-03 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('lista_numerada', 'Lista Numerada'), ('checklist', 'Checklist'), ('pix', 'PIX')], max_length=20, verbose_name='Tipo')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('pix_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do PIX')),
                ('pix_chave', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chave PIX')),
                ('pix_favorecido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Favorecido')),
                ('pix_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemAnotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('anotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_newmedia.anotacao', verbose_name='Anotação')),
            ],
            options={
                'verbose_name': 'Item de Anotação',
                'verbose_name_plural': 'Itens de Anotação',
                'ordering': ['numero'],
            },
        ),
    ]
