# Generated by Django 6.0.2 on 2026-03-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_newmedia', '0002_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemanotacao',
            name='anotacao',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='remetente',
        ),
        migrations.DeleteModel(
            name='Anotacao',
        ),
        migrations.DeleteModel(
            name='ItemAnotacao',
        ),
        migrations.DeleteModel(
            name='Transferencia',
        ),
    ]
